services:
  - type: web
    name: whatsapp-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false